// Copyright 2017 The go-github AUTHORS. All rights reserved.
//
// Use of this source code is governed by a BSD-style
// license that can be found in the LICENSE file.

// Code generated by gen-accessors; DO NOT EDIT.

package definitions

// GetAirlineData returns the AirlineData field.
func (a *AdditionalOrderInputAirlineData) GetAirlineData() *AirlineData {
	if a == nil {
		return nil
	}
	return a.AirlineData
}

// GetLodgingData returns the LodgingData field.
func (a *AdditionalOrderInputAirlineData) GetLodgingData() *LodgingData {
	if a == nil {
		return nil
	}
	return a.LodgingData
}

// GetAdditionalInfo returns the AdditionalInfo field if it's non-nil, zero value otherwise.
func (a *Address) GetAdditionalInfo() string {
	if a == nil || a.AdditionalInfo == nil {
		return ""
	}
	return *a.AdditionalInfo
}

// GetCity returns the City field if it's non-nil, zero value otherwise.
func (a *Address) GetCity() string {
	if a == nil || a.City == nil {
		return ""
	}
	return *a.City
}

// GetCountryCode returns the CountryCode field if it's non-nil, zero value otherwise.
func (a *Address) GetCountryCode() string {
	if a == nil || a.CountryCode == nil {
		return ""
	}
	return *a.CountryCode
}

// GetHouseNumber returns the HouseNumber field if it's non-nil, zero value otherwise.
func (a *Address) GetHouseNumber() string {
	if a == nil || a.HouseNumber == nil {
		return ""
	}
	return *a.HouseNumber
}

// GetState returns the State field if it's non-nil, zero value otherwise.
func (a *Address) GetState() string {
	if a == nil || a.State == nil {
		return ""
	}
	return *a.State
}

// GetStateCode returns the StateCode field if it's non-nil, zero value otherwise.
func (a *Address) GetStateCode() string {
	if a == nil || a.StateCode == nil {
		return ""
	}
	return *a.StateCode
}

// GetStreet returns the Street field if it's non-nil, zero value otherwise.
func (a *Address) GetStreet() string {
	if a == nil || a.Street == nil {
		return ""
	}
	return *a.Street
}

// GetZip returns the Zip field if it's non-nil, zero value otherwise.
func (a *Address) GetZip() string {
	if a == nil || a.Zip == nil {
		return ""
	}
	return *a.Zip
}

// GetAgentNumericCode returns the AgentNumericCode field if it's non-nil, zero value otherwise.
func (a *AirlineData) GetAgentNumericCode() string {
	if a == nil || a.AgentNumericCode == nil {
		return ""
	}
	return *a.AgentNumericCode
}

// GetCode returns the Code field if it's non-nil, zero value otherwise.
func (a *AirlineData) GetCode() string {
	if a == nil || a.Code == nil {
		return ""
	}
	return *a.Code
}

// GetFlightDate returns the FlightDate field if it's non-nil, zero value otherwise.
func (a *AirlineData) GetFlightDate() string {
	if a == nil || a.FlightDate == nil {
		return ""
	}
	return *a.FlightDate
}

// GetFlightLegs returns the FlightLegs field if it's non-nil, zero value otherwise.
func (a *AirlineData) GetFlightLegs() []AirlineFlightLeg {
	if a == nil || a.FlightLegs == nil {
		return nil
	}
	return *a.FlightLegs
}

// GetInvoiceNumber returns the InvoiceNumber field if it's non-nil, zero value otherwise.
func (a *AirlineData) GetInvoiceNumber() string {
	if a == nil || a.InvoiceNumber == nil {
		return ""
	}
	return *a.InvoiceNumber
}

// GetIsETicket returns the IsETicket field if it's non-nil, zero value otherwise.
func (a *AirlineData) GetIsETicket() bool {
	if a == nil || a.IsETicket == nil {
		return false
	}
	return *a.IsETicket
}

// GetIsRegisteredCustomer returns the IsRegisteredCustomer field if it's non-nil, zero value otherwise.
func (a *AirlineData) GetIsRegisteredCustomer() bool {
	if a == nil || a.IsRegisteredCustomer == nil {
		return false
	}
	return *a.IsRegisteredCustomer
}

// GetIsRestrictedTicket returns the IsRestrictedTicket field if it's non-nil, zero value otherwise.
func (a *AirlineData) GetIsRestrictedTicket() bool {
	if a == nil || a.IsRestrictedTicket == nil {
		return false
	}
	return *a.IsRestrictedTicket
}

// GetIssueDate returns the IssueDate field if it's non-nil, zero value otherwise.
func (a *AirlineData) GetIssueDate() string {
	if a == nil || a.IssueDate == nil {
		return ""
	}
	return *a.IssueDate
}

// GetIsThirdParty returns the IsThirdParty field if it's non-nil, zero value otherwise.
func (a *AirlineData) GetIsThirdParty() bool {
	if a == nil || a.IsThirdParty == nil {
		return false
	}
	return *a.IsThirdParty
}

// GetMerchantCustomerID returns the MerchantCustomerID field if it's non-nil, zero value otherwise.
func (a *AirlineData) GetMerchantCustomerID() string {
	if a == nil || a.MerchantCustomerID == nil {
		return ""
	}
	return *a.MerchantCustomerID
}

// GetName returns the Name field if it's non-nil, zero value otherwise.
func (a *AirlineData) GetName() string {
	if a == nil || a.Name == nil {
		return ""
	}
	return *a.Name
}

// GetPassengerName returns the PassengerName field if it's non-nil, zero value otherwise.
func (a *AirlineData) GetPassengerName() string {
	if a == nil || a.PassengerName == nil {
		return ""
	}
	return *a.PassengerName
}

// GetPassengers returns the Passengers field if it's non-nil, zero value otherwise.
func (a *AirlineData) GetPassengers() []AirlinePassenger {
	if a == nil || a.Passengers == nil {
		return nil
	}
	return *a.Passengers
}

// GetPlaceOfIssue returns the PlaceOfIssue field if it's non-nil, zero value otherwise.
func (a *AirlineData) GetPlaceOfIssue() string {
	if a == nil || a.PlaceOfIssue == nil {
		return ""
	}
	return *a.PlaceOfIssue
}

// GetPNR returns the PNR field if it's non-nil, zero value otherwise.
func (a *AirlineData) GetPNR() string {
	if a == nil || a.PNR == nil {
		return ""
	}
	return *a.PNR
}

// GetPointOfSale returns the PointOfSale field if it's non-nil, zero value otherwise.
func (a *AirlineData) GetPointOfSale() string {
	if a == nil || a.PointOfSale == nil {
		return ""
	}
	return *a.PointOfSale
}

// GetPosCityCode returns the PosCityCode field if it's non-nil, zero value otherwise.
func (a *AirlineData) GetPosCityCode() string {
	if a == nil || a.PosCityCode == nil {
		return ""
	}
	return *a.PosCityCode
}

// GetTicketDeliveryMethod returns the TicketDeliveryMethod field if it's non-nil, zero value otherwise.
func (a *AirlineData) GetTicketDeliveryMethod() string {
	if a == nil || a.TicketDeliveryMethod == nil {
		return ""
	}
	return *a.TicketDeliveryMethod
}

// GetTicketNumber returns the TicketNumber field if it's non-nil, zero value otherwise.
func (a *AirlineData) GetTicketNumber() string {
	if a == nil || a.TicketNumber == nil {
		return ""
	}
	return *a.TicketNumber
}

// GetTotalFare returns the TotalFare field if it's non-nil, zero value otherwise.
func (a *AirlineData) GetTotalFare() int32 {
	if a == nil || a.TotalFare == nil {
		return 0
	}
	return *a.TotalFare
}

// GetTotalFee returns the TotalFee field if it's non-nil, zero value otherwise.
func (a *AirlineData) GetTotalFee() int32 {
	if a == nil || a.TotalFee == nil {
		return 0
	}
	return *a.TotalFee
}

// GetTotalTaxes returns the TotalTaxes field if it's non-nil, zero value otherwise.
func (a *AirlineData) GetTotalTaxes() int32 {
	if a == nil || a.TotalTaxes == nil {
		return 0
	}
	return *a.TotalTaxes
}

// GetTravelAgencyName returns the TravelAgencyName field if it's non-nil, zero value otherwise.
func (a *AirlineData) GetTravelAgencyName() string {
	if a == nil || a.TravelAgencyName == nil {
		return ""
	}
	return *a.TravelAgencyName
}

// GetAirlineClass returns the AirlineClass field if it's non-nil, zero value otherwise.
func (a *AirlineFlightLeg) GetAirlineClass() string {
	if a == nil || a.AirlineClass == nil {
		return ""
	}
	return *a.AirlineClass
}

// GetArrivalAirport returns the ArrivalAirport field if it's non-nil, zero value otherwise.
func (a *AirlineFlightLeg) GetArrivalAirport() string {
	if a == nil || a.ArrivalAirport == nil {
		return ""
	}
	return *a.ArrivalAirport
}

// GetArrivalTime returns the ArrivalTime field if it's non-nil, zero value otherwise.
func (a *AirlineFlightLeg) GetArrivalTime() string {
	if a == nil || a.ArrivalTime == nil {
		return ""
	}
	return *a.ArrivalTime
}

// GetCarrierCode returns the CarrierCode field if it's non-nil, zero value otherwise.
func (a *AirlineFlightLeg) GetCarrierCode() string {
	if a == nil || a.CarrierCode == nil {
		return ""
	}
	return *a.CarrierCode
}

// GetConjunctionTicket returns the ConjunctionTicket field if it's non-nil, zero value otherwise.
func (a *AirlineFlightLeg) GetConjunctionTicket() string {
	if a == nil || a.ConjunctionTicket == nil {
		return ""
	}
	return *a.ConjunctionTicket
}

// GetCouponNumber returns the CouponNumber field if it's non-nil, zero value otherwise.
func (a *AirlineFlightLeg) GetCouponNumber() string {
	if a == nil || a.CouponNumber == nil {
		return ""
	}
	return *a.CouponNumber
}

// GetDate returns the Date field if it's non-nil, zero value otherwise.
func (a *AirlineFlightLeg) GetDate() string {
	if a == nil || a.Date == nil {
		return ""
	}
	return *a.Date
}

// GetDepartureTime returns the DepartureTime field if it's non-nil, zero value otherwise.
func (a *AirlineFlightLeg) GetDepartureTime() string {
	if a == nil || a.DepartureTime == nil {
		return ""
	}
	return *a.DepartureTime
}

// GetEndorsementOrRestriction returns the EndorsementOrRestriction field if it's non-nil, zero value otherwise.
func (a *AirlineFlightLeg) GetEndorsementOrRestriction() string {
	if a == nil || a.EndorsementOrRestriction == nil {
		return ""
	}
	return *a.EndorsementOrRestriction
}

// GetExchangeTicket returns the ExchangeTicket field if it's non-nil, zero value otherwise.
func (a *AirlineFlightLeg) GetExchangeTicket() string {
	if a == nil || a.ExchangeTicket == nil {
		return ""
	}
	return *a.ExchangeTicket
}

// GetFare returns the Fare field if it's non-nil, zero value otherwise.
func (a *AirlineFlightLeg) GetFare() string {
	if a == nil || a.Fare == nil {
		return ""
	}
	return *a.Fare
}

// GetFareBasis returns the FareBasis field if it's non-nil, zero value otherwise.
func (a *AirlineFlightLeg) GetFareBasis() string {
	if a == nil || a.FareBasis == nil {
		return ""
	}
	return *a.FareBasis
}

// GetFee returns the Fee field if it's non-nil, zero value otherwise.
func (a *AirlineFlightLeg) GetFee() int32 {
	if a == nil || a.Fee == nil {
		return 0
	}
	return *a.Fee
}

// GetFlightNumber returns the FlightNumber field if it's non-nil, zero value otherwise.
func (a *AirlineFlightLeg) GetFlightNumber() string {
	if a == nil || a.FlightNumber == nil {
		return ""
	}
	return *a.FlightNumber
}

// GetNumber returns the Number field if it's non-nil, zero value otherwise.
func (a *AirlineFlightLeg) GetNumber() int32 {
	if a == nil || a.Number == nil {
		return 0
	}
	return *a.Number
}

// GetOriginAirport returns the OriginAirport field if it's non-nil, zero value otherwise.
func (a *AirlineFlightLeg) GetOriginAirport() string {
	if a == nil || a.OriginAirport == nil {
		return ""
	}
	return *a.OriginAirport
}

// GetPassengerClass returns the PassengerClass field if it's non-nil, zero value otherwise.
func (a *AirlineFlightLeg) GetPassengerClass() string {
	if a == nil || a.PassengerClass == nil {
		return ""
	}
	return *a.PassengerClass
}

// GetServiceClass returns the ServiceClass field if it's non-nil, zero value otherwise.
func (a *AirlineFlightLeg) GetServiceClass() string {
	if a == nil || a.ServiceClass == nil {
		return ""
	}
	return *a.ServiceClass
}

// GetStopoverCode returns the StopoverCode field if it's non-nil, zero value otherwise.
func (a *AirlineFlightLeg) GetStopoverCode() string {
	if a == nil || a.StopoverCode == nil {
		return ""
	}
	return *a.StopoverCode
}

// GetTaxes returns the Taxes field if it's non-nil, zero value otherwise.
func (a *AirlineFlightLeg) GetTaxes() int32 {
	if a == nil || a.Taxes == nil {
		return 0
	}
	return *a.Taxes
}

// GetFirstName returns the FirstName field if it's non-nil, zero value otherwise.
func (a *AirlinePassenger) GetFirstName() string {
	if a == nil || a.FirstName == nil {
		return ""
	}
	return *a.FirstName
}

// GetSurname returns the Surname field if it's non-nil, zero value otherwise.
func (a *AirlinePassenger) GetSurname() string {
	if a == nil || a.Surname == nil {
		return ""
	}
	return *a.Surname
}

// GetSurnamePrefix returns the SurnamePrefix field if it's non-nil, zero value otherwise.
func (a *AirlinePassenger) GetSurnamePrefix() string {
	if a == nil || a.SurnamePrefix == nil {
		return ""
	}
	return *a.SurnamePrefix
}

// GetTitle returns the Title field if it's non-nil, zero value otherwise.
func (a *AirlinePassenger) GetTitle() string {
	if a == nil || a.Title == nil {
		return ""
	}
	return *a.Title
}

// GetAmount returns the Amount field if it's non-nil, zero value otherwise.
func (a *AmountOfMoney) GetAmount() int64 {
	if a == nil || a.Amount == nil {
		return 0
	}
	return *a.Amount
}

// GetCurrencyCode returns the CurrencyCode field if it's non-nil, zero value otherwise.
func (a *AmountOfMoney) GetCurrencyCode() string {
	if a == nil || a.CurrencyCode == nil {
		return ""
	}
	return *a.CurrencyCode
}

// GetAccountHolderName returns the AccountHolderName field if it's non-nil, zero value otherwise.
func (b *BankAccountBban) GetAccountHolderName() string {
	if b == nil || b.AccountHolderName == nil {
		return ""
	}
	return *b.AccountHolderName
}

// GetAccountNumber returns the AccountNumber field if it's non-nil, zero value otherwise.
func (b *BankAccountBban) GetAccountNumber() string {
	if b == nil || b.AccountNumber == nil {
		return ""
	}
	return *b.AccountNumber
}

// GetBankCode returns the BankCode field if it's non-nil, zero value otherwise.
func (b *BankAccountBban) GetBankCode() string {
	if b == nil || b.BankCode == nil {
		return ""
	}
	return *b.BankCode
}

// GetBankName returns the BankName field if it's non-nil, zero value otherwise.
func (b *BankAccountBban) GetBankName() string {
	if b == nil || b.BankName == nil {
		return ""
	}
	return *b.BankName
}

// GetBranchCode returns the BranchCode field if it's non-nil, zero value otherwise.
func (b *BankAccountBban) GetBranchCode() string {
	if b == nil || b.BranchCode == nil {
		return ""
	}
	return *b.BranchCode
}

// GetCheckDigit returns the CheckDigit field if it's non-nil, zero value otherwise.
func (b *BankAccountBban) GetCheckDigit() string {
	if b == nil || b.CheckDigit == nil {
		return ""
	}
	return *b.CheckDigit
}

// GetCountryCode returns the CountryCode field if it's non-nil, zero value otherwise.
func (b *BankAccountBban) GetCountryCode() string {
	if b == nil || b.CountryCode == nil {
		return ""
	}
	return *b.CountryCode
}

// GetAccountHolderName returns the AccountHolderName field if it's non-nil, zero value otherwise.
func (b *BankAccountIban) GetAccountHolderName() string {
	if b == nil || b.AccountHolderName == nil {
		return ""
	}
	return *b.AccountHolderName
}

// GetIban returns the Iban field if it's non-nil, zero value otherwise.
func (b *BankAccountIban) GetIban() string {
	if b == nil || b.Iban == nil {
		return ""
	}
	return *b.Iban
}

// GetCardholderName returns the CardholderName field if it's non-nil, zero value otherwise.
func (c *Card) GetCardholderName() string {
	if c == nil || c.CardholderName == nil {
		return ""
	}
	return *c.CardholderName
}

// GetCardNumber returns the CardNumber field if it's non-nil, zero value otherwise.
func (c *Card) GetCardNumber() string {
	if c == nil || c.CardNumber == nil {
		return ""
	}
	return *c.CardNumber
}

// GetCvv returns the Cvv field if it's non-nil, zero value otherwise.
func (c *Card) GetCvv() string {
	if c == nil || c.Cvv == nil {
		return ""
	}
	return *c.Cvv
}

// GetExpiryDate returns the ExpiryDate field if it's non-nil, zero value otherwise.
func (c *Card) GetExpiryDate() string {
	if c == nil || c.ExpiryDate == nil {
		return ""
	}
	return *c.ExpiryDate
}

// GetIssueNumber returns the IssueNumber field if it's non-nil, zero value otherwise.
func (c *Card) GetIssueNumber() string {
	if c == nil || c.IssueNumber == nil {
		return ""
	}
	return *c.IssueNumber
}

// GetCardNumber returns the CardNumber field if it's non-nil, zero value otherwise.
func (c *CardEssentials) GetCardNumber() string {
	if c == nil || c.CardNumber == nil {
		return ""
	}
	return *c.CardNumber
}

// GetExpiryDate returns the ExpiryDate field if it's non-nil, zero value otherwise.
func (c *CardEssentials) GetExpiryDate() string {
	if c == nil || c.ExpiryDate == nil {
		return ""
	}
	return *c.ExpiryDate
}

// GetAvsResult returns the AvsResult field if it's non-nil, zero value otherwise.
func (c *CardFraudResults) GetAvsResult() string {
	if c == nil || c.AvsResult == nil {
		return ""
	}
	return *c.AvsResult
}

// GetCvvResult returns the CvvResult field if it's non-nil, zero value otherwise.
func (c *CardFraudResults) GetCvvResult() string {
	if c == nil || c.CvvResult == nil {
		return ""
	}
	return *c.CvvResult
}

// GetFraudServiceResult returns the FraudServiceResult field if it's non-nil, zero value otherwise.
func (c *CardFraudResults) GetFraudServiceResult() string {
	if c == nil || c.FraudServiceResult == nil {
		return ""
	}
	return *c.FraudServiceResult
}

// GetFraugster returns the Fraugster field.
func (c *CardFraudResults) GetFraugster() *FraugsterResults {
	if c == nil {
		return nil
	}
	return c.Fraugster
}

// GetInAuth returns the InAuth field.
func (c *CardFraudResults) GetInAuth() *InAuth {
	if c == nil {
		return nil
	}
	return c.InAuth
}

// GetRetailDecisions returns the RetailDecisions field.
func (c *CardFraudResults) GetRetailDecisions() *FraudResultsRetailDecisions {
	if c == nil {
		return nil
	}
	return c.RetailDecisions
}

// GetCardholderName returns the CardholderName field if it's non-nil, zero value otherwise.
func (c *CardWithoutCvv) GetCardholderName() string {
	if c == nil || c.CardholderName == nil {
		return ""
	}
	return *c.CardholderName
}

// GetCardNumber returns the CardNumber field if it's non-nil, zero value otherwise.
func (c *CardWithoutCvv) GetCardNumber() string {
	if c == nil || c.CardNumber == nil {
		return ""
	}
	return *c.CardNumber
}

// GetExpiryDate returns the ExpiryDate field if it's non-nil, zero value otherwise.
func (c *CardWithoutCvv) GetExpiryDate() string {
	if c == nil || c.ExpiryDate == nil {
		return ""
	}
	return *c.ExpiryDate
}

// GetIssueNumber returns the IssueNumber field if it's non-nil, zero value otherwise.
func (c *CardWithoutCvv) GetIssueNumber() string {
	if c == nil || c.IssueNumber == nil {
		return ""
	}
	return *c.IssueNumber
}

// GetName returns the Name field if it's non-nil, zero value otherwise.
func (c *CompanyInformation) GetName() string {
	if c == nil || c.Name == nil {
		return ""
	}
	return *c.Name
}

// GetVatNumber returns the VatNumber field if it's non-nil, zero value otherwise.
func (c *CompanyInformation) GetVatNumber() string {
	if c == nil || c.VatNumber == nil {
		return ""
	}
	return *c.VatNumber
}

// GetEmailAddress returns the EmailAddress field if it's non-nil, zero value otherwise.
func (c *ContactDetailsBase) GetEmailAddress() string {
	if c == nil || c.EmailAddress == nil {
		return ""
	}
	return *c.EmailAddress
}

// GetEmailMessageType returns the EmailMessageType field if it's non-nil, zero value otherwise.
func (c *ContactDetailsBase) GetEmailMessageType() string {
	if c == nil || c.EmailMessageType == nil {
		return ""
	}
	return *c.EmailMessageType
}

// GetAddressesAreIdentical returns the AddressesAreIdentical field if it's non-nil, zero value otherwise.
func (f *FraudFields) GetAddressesAreIdentical() bool {
	if f == nil || f.AddressesAreIdentical == nil {
		return false
	}
	return *f.AddressesAreIdentical
}

// GetBlackListData returns the BlackListData field if it's non-nil, zero value otherwise.
func (f *FraudFields) GetBlackListData() string {
	if f == nil || f.BlackListData == nil {
		return ""
	}
	return *f.BlackListData
}

// GetCardOwnerAddress returns the CardOwnerAddress field.
func (f *FraudFields) GetCardOwnerAddress() *Address {
	if f == nil {
		return nil
	}
	return f.CardOwnerAddress
}

// GetCustomerIPAddress returns the CustomerIPAddress field if it's non-nil, zero value otherwise.
func (f *FraudFields) GetCustomerIPAddress() string {
	if f == nil || f.CustomerIPAddress == nil {
		return ""
	}
	return *f.CustomerIPAddress
}

// GetDefaultFormFill returns the DefaultFormFill field if it's non-nil, zero value otherwise.
func (f *FraudFields) GetDefaultFormFill() string {
	if f == nil || f.DefaultFormFill == nil {
		return ""
	}
	return *f.DefaultFormFill
}

// GetDeviceFingerprintActivated returns the DeviceFingerprintActivated field if it's non-nil, zero value otherwise.
func (f *FraudFields) GetDeviceFingerprintActivated() bool {
	if f == nil || f.DeviceFingerprintActivated == nil {
		return false
	}
	return *f.DeviceFingerprintActivated
}

// GetDeviceFingerprintTransactionID returns the DeviceFingerprintTransactionID field if it's non-nil, zero value otherwise.
func (f *FraudFields) GetDeviceFingerprintTransactionID() string {
	if f == nil || f.DeviceFingerprintTransactionID == nil {
		return ""
	}
	return *f.DeviceFingerprintTransactionID
}

// GetGiftCardType returns the GiftCardType field if it's non-nil, zero value otherwise.
func (f *FraudFields) GetGiftCardType() string {
	if f == nil || f.GiftCardType == nil {
		return ""
	}
	return *f.GiftCardType
}

// GetGiftMessage returns the GiftMessage field if it's non-nil, zero value otherwise.
func (f *FraudFields) GetGiftMessage() string {
	if f == nil || f.GiftMessage == nil {
		return ""
	}
	return *f.GiftMessage
}

// GetHasForgottenPwd returns the HasForgottenPwd field if it's non-nil, zero value otherwise.
func (f *FraudFields) GetHasForgottenPwd() bool {
	if f == nil || f.HasForgottenPwd == nil {
		return false
	}
	return *f.HasForgottenPwd
}

// GetHasPassword returns the HasPassword field if it's non-nil, zero value otherwise.
func (f *FraudFields) GetHasPassword() bool {
	if f == nil || f.HasPassword == nil {
		return false
	}
	return *f.HasPassword
}

// GetIsPreviousCustomer returns the IsPreviousCustomer field if it's non-nil, zero value otherwise.
func (f *FraudFields) GetIsPreviousCustomer() bool {
	if f == nil || f.IsPreviousCustomer == nil {
		return false
	}
	return *f.IsPreviousCustomer
}

// GetOrderTimezone returns the OrderTimezone field if it's non-nil, zero value otherwise.
func (f *FraudFields) GetOrderTimezone() string {
	if f == nil || f.OrderTimezone == nil {
		return ""
	}
	return *f.OrderTimezone
}

// GetShipComments returns the ShipComments field if it's non-nil, zero value otherwise.
func (f *FraudFields) GetShipComments() string {
	if f == nil || f.ShipComments == nil {
		return ""
	}
	return *f.ShipComments
}

// GetShipmentTrackingNumber returns the ShipmentTrackingNumber field if it's non-nil, zero value otherwise.
func (f *FraudFields) GetShipmentTrackingNumber() string {
	if f == nil || f.ShipmentTrackingNumber == nil {
		return ""
	}
	return *f.ShipmentTrackingNumber
}

// GetShippingDetails returns the ShippingDetails field.
func (f *FraudFields) GetShippingDetails() *FraudFieldsShippingDetails {
	if f == nil {
		return nil
	}
	return f.ShippingDetails
}

// GetUserData returns the UserData field if it's non-nil, zero value otherwise.
func (f *FraudFields) GetUserData() []string {
	if f == nil || f.UserData == nil {
		return nil
	}
	return *f.UserData
}

// GetWebsite returns the Website field if it's non-nil, zero value otherwise.
func (f *FraudFields) GetWebsite() string {
	if f == nil || f.Website == nil {
		return ""
	}
	return *f.Website
}

// GetMethodDetails returns the MethodDetails field if it's non-nil, zero value otherwise.
func (f *FraudFieldsShippingDetails) GetMethodDetails() string {
	if f == nil || f.MethodDetails == nil {
		return ""
	}
	return *f.MethodDetails
}

// GetMethodSpeed returns the MethodSpeed field if it's non-nil, zero value otherwise.
func (f *FraudFieldsShippingDetails) GetMethodSpeed() int32 {
	if f == nil || f.MethodSpeed == nil {
		return 0
	}
	return *f.MethodSpeed
}

// GetMethodType returns the MethodType field if it's non-nil, zero value otherwise.
func (f *FraudFieldsShippingDetails) GetMethodType() int32 {
	if f == nil || f.MethodType == nil {
		return 0
	}
	return *f.MethodType
}

// GetFraudServiceResult returns the FraudServiceResult field if it's non-nil, zero value otherwise.
func (f *FraudResults) GetFraudServiceResult() string {
	if f == nil || f.FraudServiceResult == nil {
		return ""
	}
	return *f.FraudServiceResult
}

// GetInAuth returns the InAuth field.
func (f *FraudResults) GetInAuth() *InAuth {
	if f == nil {
		return nil
	}
	return f.InAuth
}

// GetFraudCode returns the FraudCode field if it's non-nil, zero value otherwise.
func (f *FraudResultsRetailDecisions) GetFraudCode() string {
	if f == nil || f.FraudCode == nil {
		return ""
	}
	return *f.FraudCode
}

// GetFraudNeural returns the FraudNeural field if it's non-nil, zero value otherwise.
func (f *FraudResultsRetailDecisions) GetFraudNeural() string {
	if f == nil || f.FraudNeural == nil {
		return ""
	}
	return *f.FraudNeural
}

// GetFraudRCF returns the FraudRCF field if it's non-nil, zero value otherwise.
func (f *FraudResultsRetailDecisions) GetFraudRCF() string {
	if f == nil || f.FraudRCF == nil {
		return ""
	}
	return *f.FraudRCF
}

// GetFraudInvestigationPoints returns the FraudInvestigationPoints field if it's non-nil, zero value otherwise.
func (f *FraugsterResults) GetFraudInvestigationPoints() string {
	if f == nil || f.FraudInvestigationPoints == nil {
		return ""
	}
	return *f.FraudInvestigationPoints
}

// GetFraudScore returns the FraudScore field if it's non-nil, zero value otherwise.
func (f *FraugsterResults) GetFraudScore() int32 {
	if f == nil || f.FraudScore == nil {
		return 0
	}
	return *f.FraudScore
}

// GetDeviceCategory returns the DeviceCategory field if it's non-nil, zero value otherwise.
func (i *InAuth) GetDeviceCategory() string {
	if i == nil || i.DeviceCategory == nil {
		return ""
	}
	return *i.DeviceCategory
}

// GetDeviceID returns the DeviceID field if it's non-nil, zero value otherwise.
func (i *InAuth) GetDeviceID() string {
	if i == nil || i.DeviceID == nil {
		return ""
	}
	return *i.DeviceID
}

// GetRiskScore returns the RiskScore field if it's non-nil, zero value otherwise.
func (i *InAuth) GetRiskScore() string {
	if i == nil || i.RiskScore == nil {
		return ""
	}
	return *i.RiskScore
}

// GetTrueIPAddress returns the TrueIPAddress field if it's non-nil, zero value otherwise.
func (i *InAuth) GetTrueIPAddress() string {
	if i == nil || i.TrueIPAddress == nil {
		return ""
	}
	return *i.TrueIPAddress
}

// GetTrueIPAddressCountry returns the TrueIPAddressCountry field if it's non-nil, zero value otherwise.
func (i *InAuth) GetTrueIPAddressCountry() string {
	if i == nil || i.TrueIPAddressCountry == nil {
		return ""
	}
	return *i.TrueIPAddressCountry
}

// GetKey returns the Key field if it's non-nil, zero value otherwise.
func (k *KeyValuePair) GetKey() string {
	if k == nil || k.Key == nil {
		return ""
	}
	return *k.Key
}

// GetValue returns the Value field if it's non-nil, zero value otherwise.
func (k *KeyValuePair) GetValue() string {
	if k == nil || k.Value == nil {
		return ""
	}
	return *k.Value
}

// GetChargeAmount returns the ChargeAmount field if it's non-nil, zero value otherwise.
func (l *LodgingCharge) GetChargeAmount() int64 {
	if l == nil || l.ChargeAmount == nil {
		return 0
	}
	return *l.ChargeAmount
}

// GetChargeAmountCurrencyCode returns the ChargeAmountCurrencyCode field if it's non-nil, zero value otherwise.
func (l *LodgingCharge) GetChargeAmountCurrencyCode() string {
	if l == nil || l.ChargeAmountCurrencyCode == nil {
		return ""
	}
	return *l.ChargeAmountCurrencyCode
}

// GetChargeType returns the ChargeType field if it's non-nil, zero value otherwise.
func (l *LodgingCharge) GetChargeType() string {
	if l == nil || l.ChargeType == nil {
		return ""
	}
	return *l.ChargeType
}

// GetCharges returns the Charges field if it's non-nil, zero value otherwise.
func (l *LodgingData) GetCharges() []LodgingCharge {
	if l == nil || l.Charges == nil {
		return nil
	}
	return *l.Charges
}

// GetCheckInDate returns the CheckInDate field if it's non-nil, zero value otherwise.
func (l *LodgingData) GetCheckInDate() string {
	if l == nil || l.CheckInDate == nil {
		return ""
	}
	return *l.CheckInDate
}

// GetCheckOutDate returns the CheckOutDate field if it's non-nil, zero value otherwise.
func (l *LodgingData) GetCheckOutDate() string {
	if l == nil || l.CheckOutDate == nil {
		return ""
	}
	return *l.CheckOutDate
}

// GetFolioNumber returns the FolioNumber field if it's non-nil, zero value otherwise.
func (l *LodgingData) GetFolioNumber() string {
	if l == nil || l.FolioNumber == nil {
		return ""
	}
	return *l.FolioNumber
}

// GetIsConfirmedReservation returns the IsConfirmedReservation field if it's non-nil, zero value otherwise.
func (l *LodgingData) GetIsConfirmedReservation() bool {
	if l == nil || l.IsConfirmedReservation == nil {
		return false
	}
	return *l.IsConfirmedReservation
}

// GetIsFacilityFireSafetyConform returns the IsFacilityFireSafetyConform field if it's non-nil, zero value otherwise.
func (l *LodgingData) GetIsFacilityFireSafetyConform() bool {
	if l == nil || l.IsFacilityFireSafetyConform == nil {
		return false
	}
	return *l.IsFacilityFireSafetyConform
}

// GetIsNoShow returns the IsNoShow field if it's non-nil, zero value otherwise.
func (l *LodgingData) GetIsNoShow() bool {
	if l == nil || l.IsNoShow == nil {
		return false
	}
	return *l.IsNoShow
}

// GetIsPreferenceSmokingRoom returns the IsPreferenceSmokingRoom field if it's non-nil, zero value otherwise.
func (l *LodgingData) GetIsPreferenceSmokingRoom() bool {
	if l == nil || l.IsPreferenceSmokingRoom == nil {
		return false
	}
	return *l.IsPreferenceSmokingRoom
}

// GetNumberOfAdults returns the NumberOfAdults field if it's non-nil, zero value otherwise.
func (l *LodgingData) GetNumberOfAdults() int32 {
	if l == nil || l.NumberOfAdults == nil {
		return 0
	}
	return *l.NumberOfAdults
}

// GetNumberOfNights returns the NumberOfNights field if it's non-nil, zero value otherwise.
func (l *LodgingData) GetNumberOfNights() int32 {
	if l == nil || l.NumberOfNights == nil {
		return 0
	}
	return *l.NumberOfNights
}

// GetNumberOfRooms returns the NumberOfRooms field if it's non-nil, zero value otherwise.
func (l *LodgingData) GetNumberOfRooms() int32 {
	if l == nil || l.NumberOfRooms == nil {
		return 0
	}
	return *l.NumberOfRooms
}

// GetProgramCode returns the ProgramCode field if it's non-nil, zero value otherwise.
func (l *LodgingData) GetProgramCode() string {
	if l == nil || l.ProgramCode == nil {
		return ""
	}
	return *l.ProgramCode
}

// GetPropertyCustomerServicePhoneNumber returns the PropertyCustomerServicePhoneNumber field if it's non-nil, zero value otherwise.
func (l *LodgingData) GetPropertyCustomerServicePhoneNumber() string {
	if l == nil || l.PropertyCustomerServicePhoneNumber == nil {
		return ""
	}
	return *l.PropertyCustomerServicePhoneNumber
}

// GetPropertyPhoneNumber returns the PropertyPhoneNumber field if it's non-nil, zero value otherwise.
func (l *LodgingData) GetPropertyPhoneNumber() string {
	if l == nil || l.PropertyPhoneNumber == nil {
		return ""
	}
	return *l.PropertyPhoneNumber
}

// GetRenterName returns the RenterName field if it's non-nil, zero value otherwise.
func (l *LodgingData) GetRenterName() string {
	if l == nil || l.RenterName == nil {
		return ""
	}
	return *l.RenterName
}

// GetRooms returns the Rooms field if it's non-nil, zero value otherwise.
func (l *LodgingData) GetRooms() []LodgingRoom {
	if l == nil || l.Rooms == nil {
		return nil
	}
	return *l.Rooms
}

// GetDailyRoomRate returns the DailyRoomRate field if it's non-nil, zero value otherwise.
func (l *LodgingRoom) GetDailyRoomRate() string {
	if l == nil || l.DailyRoomRate == nil {
		return ""
	}
	return *l.DailyRoomRate
}

// GetDailyRoomRateCurrencyCode returns the DailyRoomRateCurrencyCode field if it's non-nil, zero value otherwise.
func (l *LodgingRoom) GetDailyRoomRateCurrencyCode() string {
	if l == nil || l.DailyRoomRateCurrencyCode == nil {
		return ""
	}
	return *l.DailyRoomRateCurrencyCode
}

// GetDailyRoomTaxAmount returns the DailyRoomTaxAmount field if it's non-nil, zero value otherwise.
func (l *LodgingRoom) GetDailyRoomTaxAmount() string {
	if l == nil || l.DailyRoomTaxAmount == nil {
		return ""
	}
	return *l.DailyRoomTaxAmount
}

// GetDailyRoomTaxAmountCurrencyCode returns the DailyRoomTaxAmountCurrencyCode field if it's non-nil, zero value otherwise.
func (l *LodgingRoom) GetDailyRoomTaxAmountCurrencyCode() string {
	if l == nil || l.DailyRoomTaxAmountCurrencyCode == nil {
		return ""
	}
	return *l.DailyRoomTaxAmountCurrencyCode
}

// GetNumberOfNightsAtRoomRate returns the NumberOfNightsAtRoomRate field if it's non-nil, zero value otherwise.
func (l *LodgingRoom) GetNumberOfNightsAtRoomRate() int32 {
	if l == nil || l.NumberOfNightsAtRoomRate == nil {
		return 0
	}
	return *l.NumberOfNightsAtRoomRate
}

// GetRoomLocation returns the RoomLocation field if it's non-nil, zero value otherwise.
func (l *LodgingRoom) GetRoomLocation() string {
	if l == nil || l.RoomLocation == nil {
		return ""
	}
	return *l.RoomLocation
}

// GetRoomNumber returns the RoomNumber field if it's non-nil, zero value otherwise.
func (l *LodgingRoom) GetRoomNumber() string {
	if l == nil || l.RoomNumber == nil {
		return ""
	}
	return *l.RoomNumber
}

// GetTypeOfBed returns the TypeOfBed field if it's non-nil, zero value otherwise.
func (l *LodgingRoom) GetTypeOfBed() string {
	if l == nil || l.TypeOfBed == nil {
		return ""
	}
	return *l.TypeOfBed
}

// GetTypeOfRoom returns the TypeOfRoom field if it's non-nil, zero value otherwise.
func (l *LodgingRoom) GetTypeOfRoom() string {
	if l == nil || l.TypeOfRoom == nil {
		return ""
	}
	return *l.TypeOfRoom
}

// GetIsCancellable returns the IsCancellable field if it's non-nil, zero value otherwise.
func (o *OrderStatusOutput) GetIsCancellable() bool {
	if o == nil || o.IsCancellable == nil {
		return false
	}
	return *o.IsCancellable
}

// GetStatusCategory returns the StatusCategory field if it's non-nil, zero value otherwise.
func (o *OrderStatusOutput) GetStatusCategory() string {
	if o == nil || o.StatusCategory == nil {
		return ""
	}
	return *o.StatusCategory
}

// GetStatusCode returns the StatusCode field if it's non-nil, zero value otherwise.
func (o *OrderStatusOutput) GetStatusCode() int32 {
	if o == nil || o.StatusCode == nil {
		return 0
	}
	return *o.StatusCode
}

// GetStatusCodeChangeDateTime returns the StatusCodeChangeDateTime field if it's non-nil, zero value otherwise.
func (o *OrderStatusOutput) GetStatusCodeChangeDateTime() string {
	if o == nil || o.StatusCodeChangeDateTime == nil {
		return ""
	}
	return *o.StatusCodeChangeDateTime
}

// GetGroups returns the Groups field if it's non-nil, zero value otherwise.
func (p *PaymentProductFilter) GetGroups() []string {
	if p == nil || p.Groups == nil {
		return nil
	}
	return *p.Groups
}

// GetProducts returns the Products field if it's non-nil, zero value otherwise.
func (p *PaymentProductFilter) GetProducts() []int32 {
	if p == nil || p.Products == nil {
		return nil
	}
	return *p.Products
}

// GetCategory returns the Category field if it's non-nil, zero value otherwise.
func (r *ResultDoRiskAssessment) GetCategory() string {
	if r == nil || r.Category == nil {
		return ""
	}
	return *r.Category
}

// GetResult returns the Result field if it's non-nil, zero value otherwise.
func (r *ResultDoRiskAssessment) GetResult() string {
	if r == nil || r.Result == nil {
		return ""
	}
	return *r.Result
}

// GetRetaildecisionsCCFraudCheckOutput returns the RetaildecisionsCCFraudCheckOutput field.
func (r *ResultDoRiskAssessment) GetRetaildecisionsCCFraudCheckOutput() *RetailDecisionsCCFraudCheckOutput {
	if r == nil {
		return nil
	}
	return r.RetaildecisionsCCFraudCheckOutput
}

// GetValidationBankAccountOutput returns the ValidationBankAccountOutput field.
func (r *ResultDoRiskAssessment) GetValidationBankAccountOutput() *ValidationBankAccountOutput {
	if r == nil {
		return nil
	}
	return r.ValidationBankAccountOutput
}

// GetFraudCode returns the FraudCode field if it's non-nil, zero value otherwise.
func (r *RetailDecisionsCCFraudCheckOutput) GetFraudCode() string {
	if r == nil || r.FraudCode == nil {
		return ""
	}
	return *r.FraudCode
}

// GetFraudNeural returns the FraudNeural field if it's non-nil, zero value otherwise.
func (r *RetailDecisionsCCFraudCheckOutput) GetFraudNeural() string {
	if r == nil || r.FraudNeural == nil {
		return ""
	}
	return *r.FraudNeural
}

// GetFraudRCF returns the FraudRCF field if it's non-nil, zero value otherwise.
func (r *RetailDecisionsCCFraudCheckOutput) GetFraudRCF() string {
	if r == nil || r.FraudRCF == nil {
		return ""
	}
	return *r.FraudRCF
}

// GetCode returns the Code field if it's non-nil, zero value otherwise.
func (v *ValidationBankAccountCheck) GetCode() string {
	if v == nil || v.Code == nil {
		return ""
	}
	return *v.Code
}

// GetDescription returns the Description field if it's non-nil, zero value otherwise.
func (v *ValidationBankAccountCheck) GetDescription() string {
	if v == nil || v.Description == nil {
		return ""
	}
	return *v.Description
}

// GetResult returns the Result field if it's non-nil, zero value otherwise.
func (v *ValidationBankAccountCheck) GetResult() string {
	if v == nil || v.Result == nil {
		return ""
	}
	return *v.Result
}

// GetChecks returns the Checks field if it's non-nil, zero value otherwise.
func (v *ValidationBankAccountOutput) GetChecks() []ValidationBankAccountCheck {
	if v == nil || v.Checks == nil {
		return nil
	}
	return *v.Checks
}

// GetNewBankName returns the NewBankName field if it's non-nil, zero value otherwise.
func (v *ValidationBankAccountOutput) GetNewBankName() string {
	if v == nil || v.NewBankName == nil {
		return ""
	}
	return *v.NewBankName
}

// GetReformattedAccountNumber returns the ReformattedAccountNumber field if it's non-nil, zero value otherwise.
func (v *ValidationBankAccountOutput) GetReformattedAccountNumber() string {
	if v == nil || v.ReformattedAccountNumber == nil {
		return ""
	}
	return *v.ReformattedAccountNumber
}

// GetReformattedBankCode returns the ReformattedBankCode field if it's non-nil, zero value otherwise.
func (v *ValidationBankAccountOutput) GetReformattedBankCode() string {
	if v == nil || v.ReformattedBankCode == nil {
		return ""
	}
	return *v.ReformattedBankCode
}

// GetReformattedBranchCode returns the ReformattedBranchCode field if it's non-nil, zero value otherwise.
func (v *ValidationBankAccountOutput) GetReformattedBranchCode() string {
	if v == nil || v.ReformattedBranchCode == nil {
		return ""
	}
	return *v.ReformattedBranchCode
}
