// Copyright 2017 The go-github AUTHORS. All rights reserved.
//
// Use of this source code is governed by a BSD-style
// license that can be found in the LICENSE file.

// Code generated by gen-accessors; DO NOT EDIT.

package dispute

// GetContactPerson returns the ContactPerson field if it's non-nil, zero value otherwise.
func (c *CreateRequest) GetContactPerson() string {
	if c == nil || c.ContactPerson == nil {
		return ""
	}
	return *c.ContactPerson
}

// GetEmailAddress returns the EmailAddress field if it's non-nil, zero value otherwise.
func (c *CreateRequest) GetEmailAddress() string {
	if c == nil || c.EmailAddress == nil {
		return ""
	}
	return *c.EmailAddress
}

// GetReplyTo returns the ReplyTo field if it's non-nil, zero value otherwise.
func (c *CreateRequest) GetReplyTo() string {
	if c == nil || c.ReplyTo == nil {
		return ""
	}
	return *c.ReplyTo
}

// GetRequestMessage returns the RequestMessage field if it's non-nil, zero value otherwise.
func (c *CreateRequest) GetRequestMessage() string {
	if c == nil || c.RequestMessage == nil {
		return ""
	}
	return *c.RequestMessage
}

// GetDisputeCreationDate returns the DisputeCreationDate field if it's non-nil, zero value otherwise.
func (c *CreationDetail) GetDisputeCreationDate() string {
	if c == nil || c.DisputeCreationDate == nil {
		return ""
	}
	return *c.DisputeCreationDate
}

// GetDisputeOriginator returns the DisputeOriginator field if it's non-nil, zero value otherwise.
func (c *CreationDetail) GetDisputeOriginator() string {
	if c == nil || c.DisputeOriginator == nil {
		return ""
	}
	return *c.DisputeOriginator
}

// GetUserName returns the UserName field if it's non-nil, zero value otherwise.
func (c *CreationDetail) GetUserName() string {
	if c == nil || c.UserName == nil {
		return ""
	}
	return *c.UserName
}

// GetDisputeOutput returns the DisputeOutput field.
func (d *Dispute) GetDisputeOutput() *Output {
	if d == nil {
		return nil
	}
	return d.DisputeOutput
}

// GetID returns the ID field if it's non-nil, zero value otherwise.
func (d *Dispute) GetID() string {
	if d == nil || d.ID == nil {
		return ""
	}
	return *d.ID
}

// GetPaymentID returns the PaymentID field if it's non-nil, zero value otherwise.
func (d *Dispute) GetPaymentID() string {
	if d == nil || d.PaymentID == nil {
		return ""
	}
	return *d.PaymentID
}

// GetStatus returns the Status field if it's non-nil, zero value otherwise.
func (d *Dispute) GetStatus() string {
	if d == nil || d.Status == nil {
		return ""
	}
	return *d.Status
}

// GetStatusOutput returns the StatusOutput field.
func (d *Dispute) GetStatusOutput() *StatusOutput {
	if d == nil {
		return nil
	}
	return d.StatusOutput
}

// GetDisputes returns the Disputes field if it's non-nil, zero value otherwise.
func (d *DisputesResponse) GetDisputes() []Dispute {
	if d == nil || d.Disputes == nil {
		return nil
	}
	return *d.Disputes
}

// GetContactPerson returns the ContactPerson field if it's non-nil, zero value otherwise.
func (o *Output) GetContactPerson() string {
	if o == nil || o.ContactPerson == nil {
		return ""
	}
	return *o.ContactPerson
}

// GetCreationDetails returns the CreationDetails field.
func (o *Output) GetCreationDetails() *CreationDetail {
	if o == nil {
		return nil
	}
	return o.CreationDetails
}

// GetEmailAddress returns the EmailAddress field if it's non-nil, zero value otherwise.
func (o *Output) GetEmailAddress() string {
	if o == nil || o.EmailAddress == nil {
		return ""
	}
	return *o.EmailAddress
}

// GetReference returns the Reference field.
func (o *Output) GetReference() *Reference {
	if o == nil {
		return nil
	}
	return o.Reference
}

// GetReplyTo returns the ReplyTo field if it's non-nil, zero value otherwise.
func (o *Output) GetReplyTo() string {
	if o == nil || o.ReplyTo == nil {
		return ""
	}
	return *o.ReplyTo
}

// GetRequestMessage returns the RequestMessage field if it's non-nil, zero value otherwise.
func (o *Output) GetRequestMessage() string {
	if o == nil || o.RequestMessage == nil {
		return ""
	}
	return *o.RequestMessage
}

// GetResponseMessage returns the ResponseMessage field if it's non-nil, zero value otherwise.
func (o *Output) GetResponseMessage() string {
	if o == nil || o.ResponseMessage == nil {
		return ""
	}
	return *o.ResponseMessage
}

// GetMerchantOrderID returns the MerchantOrderID field if it's non-nil, zero value otherwise.
func (r *Reference) GetMerchantOrderID() string {
	if r == nil || r.MerchantOrderID == nil {
		return ""
	}
	return *r.MerchantOrderID
}

// GetMerchantReference returns the MerchantReference field if it's non-nil, zero value otherwise.
func (r *Reference) GetMerchantReference() string {
	if r == nil || r.MerchantReference == nil {
		return ""
	}
	return *r.MerchantReference
}

// GetPaymentReference returns the PaymentReference field if it's non-nil, zero value otherwise.
func (r *Reference) GetPaymentReference() string {
	if r == nil || r.PaymentReference == nil {
		return ""
	}
	return *r.PaymentReference
}

// GetProviderID returns the ProviderID field if it's non-nil, zero value otherwise.
func (r *Reference) GetProviderID() string {
	if r == nil || r.ProviderID == nil {
		return ""
	}
	return *r.ProviderID
}

// GetProviderReference returns the ProviderReference field if it's non-nil, zero value otherwise.
func (r *Reference) GetProviderReference() string {
	if r == nil || r.ProviderReference == nil {
		return ""
	}
	return *r.ProviderReference
}

// GetDisputeOutput returns the DisputeOutput field.
func (r *Response) GetDisputeOutput() *Output {
	if r == nil {
		return nil
	}
	return r.DisputeOutput
}

// GetID returns the ID field if it's non-nil, zero value otherwise.
func (r *Response) GetID() string {
	if r == nil || r.ID == nil {
		return ""
	}
	return *r.ID
}

// GetPaymentID returns the PaymentID field if it's non-nil, zero value otherwise.
func (r *Response) GetPaymentID() string {
	if r == nil || r.PaymentID == nil {
		return ""
	}
	return *r.PaymentID
}

// GetStatus returns the Status field if it's non-nil, zero value otherwise.
func (r *Response) GetStatus() string {
	if r == nil || r.Status == nil {
		return ""
	}
	return *r.Status
}

// GetStatusOutput returns the StatusOutput field.
func (r *Response) GetStatusOutput() *StatusOutput {
	if r == nil {
		return nil
	}
	return r.StatusOutput
}

// GetIsCancellable returns the IsCancellable field if it's non-nil, zero value otherwise.
func (s *StatusOutput) GetIsCancellable() bool {
	if s == nil || s.IsCancellable == nil {
		return false
	}
	return *s.IsCancellable
}

// GetStatusCategory returns the StatusCategory field if it's non-nil, zero value otherwise.
func (s *StatusOutput) GetStatusCategory() string {
	if s == nil || s.StatusCategory == nil {
		return ""
	}
	return *s.StatusCategory
}

// GetStatusCode returns the StatusCode field if it's non-nil, zero value otherwise.
func (s *StatusOutput) GetStatusCode() int32 {
	if s == nil || s.StatusCode == nil {
		return 0
	}
	return *s.StatusCode
}

// GetStatusCodeChangeDateTime returns the StatusCodeChangeDateTime field if it's non-nil, zero value otherwise.
func (s *StatusOutput) GetStatusCodeChangeDateTime() string {
	if s == nil || s.StatusCodeChangeDateTime == nil {
		return ""
	}
	return *s.StatusCodeChangeDateTime
}

// GetDisputeID returns the DisputeID field if it's non-nil, zero value otherwise.
func (u *UploadDisputeFileResponse) GetDisputeID() string {
	if u == nil || u.DisputeID == nil {
		return ""
	}
	return *u.DisputeID
}

// GetFileID returns the FileID field if it's non-nil, zero value otherwise.
func (u *UploadDisputeFileResponse) GetFileID() string {
	if u == nil || u.FileID == nil {
		return ""
	}
	return *u.FileID
}
