// Copyright 2017 The go-github AUTHORS. All rights reserved.
//
// Use of this source code is governed by a BSD-style
// license that can be found in the LICENSE file.

// Code generated by gen-accessors; DO NOT EDIT.

package services

// GetNewBankName returns the NewBankName field if it's non-nil, zero value otherwise.
func (b *BankData) GetNewBankName() string {
	if b == nil || b.NewBankName == nil {
		return ""
	}
	return *b.NewBankName
}

// GetReformattedAccountNumber returns the ReformattedAccountNumber field if it's non-nil, zero value otherwise.
func (b *BankData) GetReformattedAccountNumber() string {
	if b == nil || b.ReformattedAccountNumber == nil {
		return ""
	}
	return *b.ReformattedAccountNumber
}

// GetReformattedBankCode returns the ReformattedBankCode field if it's non-nil, zero value otherwise.
func (b *BankData) GetReformattedBankCode() string {
	if b == nil || b.ReformattedBankCode == nil {
		return ""
	}
	return *b.ReformattedBankCode
}

// GetReformattedBranchCode returns the ReformattedBranchCode field if it's non-nil, zero value otherwise.
func (b *BankData) GetReformattedBranchCode() string {
	if b == nil || b.ReformattedBranchCode == nil {
		return ""
	}
	return *b.ReformattedBranchCode
}

// GetBankData returns the BankData field.
func (b *BankDetailsResponse) GetBankData() *BankData {
	if b == nil {
		return nil
	}
	return b.BankData
}

// GetSwift returns the Swift field.
func (b *BankDetailsResponse) GetSwift() *Swift {
	if b == nil {
		return nil
	}
	return b.Swift
}

// GetConvertedAmount returns the ConvertedAmount field if it's non-nil, zero value otherwise.
func (c *ConvertAmount) GetConvertedAmount() int64 {
	if c == nil || c.ConvertedAmount == nil {
		return 0
	}
	return *c.ConvertedAmount
}

// GetBin returns the Bin field if it's non-nil, zero value otherwise.
func (g *GetIINDetailsRequest) GetBin() string {
	if g == nil || g.Bin == nil {
		return ""
	}
	return *g.Bin
}

// GetPaymentContext returns the PaymentContext field.
func (g *GetIINDetailsRequest) GetPaymentContext() *PaymentContext {
	if g == nil {
		return nil
	}
	return g.PaymentContext
}

// GetCoBrands returns the CoBrands field if it's non-nil, zero value otherwise.
func (g *GetIINDetailsResponse) GetCoBrands() []IINDetail {
	if g == nil || g.CoBrands == nil {
		return nil
	}
	return *g.CoBrands
}

// GetCountryCode returns the CountryCode field if it's non-nil, zero value otherwise.
func (g *GetIINDetailsResponse) GetCountryCode() string {
	if g == nil || g.CountryCode == nil {
		return ""
	}
	return *g.CountryCode
}

// GetIsAllowedInContext returns the IsAllowedInContext field if it's non-nil, zero value otherwise.
func (g *GetIINDetailsResponse) GetIsAllowedInContext() bool {
	if g == nil || g.IsAllowedInContext == nil {
		return false
	}
	return *g.IsAllowedInContext
}

// GetPaymentProductID returns the PaymentProductID field if it's non-nil, zero value otherwise.
func (g *GetIINDetailsResponse) GetPaymentProductID() int32 {
	if g == nil || g.PaymentProductID == nil {
		return 0
	}
	return *g.PaymentProductID
}

// GetHTMLContent returns the HTMLContent field if it's non-nil, zero value otherwise.
func (g *GetPrivacyPolicyResponse) GetHTMLContent() string {
	if g == nil || g.HTMLContent == nil {
		return ""
	}
	return *g.HTMLContent
}

// GetIsAllowedInContext returns the IsAllowedInContext field if it's non-nil, zero value otherwise.
func (i *IINDetail) GetIsAllowedInContext() bool {
	if i == nil || i.IsAllowedInContext == nil {
		return false
	}
	return *i.IsAllowedInContext
}

// GetPaymentProductID returns the PaymentProductID field if it's non-nil, zero value otherwise.
func (i *IINDetail) GetPaymentProductID() int32 {
	if i == nil || i.PaymentProductID == nil {
		return 0
	}
	return *i.PaymentProductID
}

// GetCountryCode returns the CountryCode field if it's non-nil, zero value otherwise.
func (p *PaymentContext) GetCountryCode() string {
	if p == nil || p.CountryCode == nil {
		return ""
	}
	return *p.CountryCode
}

// GetIsRecurring returns the IsRecurring field if it's non-nil, zero value otherwise.
func (p *PaymentContext) GetIsRecurring() bool {
	if p == nil || p.IsRecurring == nil {
		return false
	}
	return *p.IsRecurring
}

// GetBic returns the Bic field if it's non-nil, zero value otherwise.
func (s *Swift) GetBic() string {
	if s == nil || s.Bic == nil {
		return ""
	}
	return *s.Bic
}

// GetCategory returns the Category field if it's non-nil, zero value otherwise.
func (s *Swift) GetCategory() string {
	if s == nil || s.Category == nil {
		return ""
	}
	return *s.Category
}

// GetChipsUID returns the ChipsUID field if it's non-nil, zero value otherwise.
func (s *Swift) GetChipsUID() string {
	if s == nil || s.ChipsUID == nil {
		return ""
	}
	return *s.ChipsUID
}

// GetExtraInfo returns the ExtraInfo field if it's non-nil, zero value otherwise.
func (s *Swift) GetExtraInfo() string {
	if s == nil || s.ExtraInfo == nil {
		return ""
	}
	return *s.ExtraInfo
}

// GetPoBoxCountry returns the PoBoxCountry field if it's non-nil, zero value otherwise.
func (s *Swift) GetPoBoxCountry() string {
	if s == nil || s.PoBoxCountry == nil {
		return ""
	}
	return *s.PoBoxCountry
}

// GetPoBoxLocation returns the PoBoxLocation field if it's non-nil, zero value otherwise.
func (s *Swift) GetPoBoxLocation() string {
	if s == nil || s.PoBoxLocation == nil {
		return ""
	}
	return *s.PoBoxLocation
}

// GetPoBoxNumber returns the PoBoxNumber field if it's non-nil, zero value otherwise.
func (s *Swift) GetPoBoxNumber() string {
	if s == nil || s.PoBoxNumber == nil {
		return ""
	}
	return *s.PoBoxNumber
}

// GetPoBoxZip returns the PoBoxZip field if it's non-nil, zero value otherwise.
func (s *Swift) GetPoBoxZip() string {
	if s == nil || s.PoBoxZip == nil {
		return ""
	}
	return *s.PoBoxZip
}

// GetRoutingBic returns the RoutingBic field if it's non-nil, zero value otherwise.
func (s *Swift) GetRoutingBic() string {
	if s == nil || s.RoutingBic == nil {
		return ""
	}
	return *s.RoutingBic
}

// GetServices returns the Services field if it's non-nil, zero value otherwise.
func (s *Swift) GetServices() string {
	if s == nil || s.Services == nil {
		return ""
	}
	return *s.Services
}

// GetResult returns the Result field if it's non-nil, zero value otherwise.
func (t *TestConnection) GetResult() string {
	if t == nil || t.Result == nil {
		return ""
	}
	return *t.Result
}
