// Copyright 2017 The go-github AUTHORS. All rights reserved.
//
// Use of this source code is governed by a BSD-style
// license that can be found in the LICENSE file.

// Code generated by gen-accessors; DO NOT EDIT.

package token

// GetMandateSignatureDate returns the MandateSignatureDate field if it's non-nil, zero value otherwise.
func (a *ApproveRequest) GetMandateSignatureDate() string {
	if a == nil || a.MandateSignatureDate == nil {
		return ""
	}
	return *a.MandateSignatureDate
}

// GetMandateSignaturePlace returns the MandateSignaturePlace field if it's non-nil, zero value otherwise.
func (a *ApproveRequest) GetMandateSignaturePlace() string {
	if a == nil || a.MandateSignaturePlace == nil {
		return ""
	}
	return *a.MandateSignaturePlace
}

// GetMandateSigned returns the MandateSigned field if it's non-nil, zero value otherwise.
func (a *ApproveRequest) GetMandateSigned() bool {
	if a == nil || a.MandateSigned == nil {
		return false
	}
	return *a.MandateSigned
}

// GetAlias returns the Alias field if it's non-nil, zero value otherwise.
func (c *Card) GetAlias() string {
	if c == nil || c.Alias == nil {
		return ""
	}
	return *c.Alias
}

// GetCustomer returns the Customer field.
func (c *Card) GetCustomer() *CustomerToken {
	if c == nil {
		return nil
	}
	return c.Customer
}

// GetData returns the Data field.
func (c *Card) GetData() *CardData {
	if c == nil {
		return nil
	}
	return c.Data
}

// GetFirstTransactionDate returns the FirstTransactionDate field if it's non-nil, zero value otherwise.
func (c *CardData) GetFirstTransactionDate() string {
	if c == nil || c.FirstTransactionDate == nil {
		return ""
	}
	return *c.FirstTransactionDate
}

// GetProviderReference returns the ProviderReference field if it's non-nil, zero value otherwise.
func (c *CardData) GetProviderReference() string {
	if c == nil || c.ProviderReference == nil {
		return ""
	}
	return *c.ProviderReference
}

// GetEmailAddress returns the EmailAddress field if it's non-nil, zero value otherwise.
func (c *ContactDetailsToken) GetEmailAddress() string {
	if c == nil || c.EmailAddress == nil {
		return ""
	}
	return *c.EmailAddress
}

// GetEmailMessageType returns the EmailMessageType field if it's non-nil, zero value otherwise.
func (c *ContactDetailsToken) GetEmailMessageType() string {
	if c == nil || c.EmailMessageType == nil {
		return ""
	}
	return *c.EmailMessageType
}

// GetCard returns the Card field.
func (c *CreateRequest) GetCard() *Card {
	if c == nil {
		return nil
	}
	return c.Card
}

// GetEncryptedCustomerInput returns the EncryptedCustomerInput field if it's non-nil, zero value otherwise.
func (c *CreateRequest) GetEncryptedCustomerInput() string {
	if c == nil || c.EncryptedCustomerInput == nil {
		return ""
	}
	return *c.EncryptedCustomerInput
}

// GetEWallet returns the EWallet field.
func (c *CreateRequest) GetEWallet() *EWallet {
	if c == nil {
		return nil
	}
	return c.EWallet
}

// GetNonSepaDirectDebit returns the NonSepaDirectDebit field.
func (c *CreateRequest) GetNonSepaDirectDebit() *NonSepaDirectDebit {
	if c == nil {
		return nil
	}
	return c.NonSepaDirectDebit
}

// GetPaymentProductID returns the PaymentProductID field if it's non-nil, zero value otherwise.
func (c *CreateRequest) GetPaymentProductID() int32 {
	if c == nil || c.PaymentProductID == nil {
		return 0
	}
	return *c.PaymentProductID
}

// GetSepaDirectDebit returns the SepaDirectDebit field.
func (c *CreateRequest) GetSepaDirectDebit() *SepaDirectDebitWithoutCreditor {
	if c == nil {
		return nil
	}
	return c.SepaDirectDebit
}

// GetIsNewToken returns the IsNewToken field if it's non-nil, zero value otherwise.
func (c *CreateResponse) GetIsNewToken() bool {
	if c == nil || c.IsNewToken == nil {
		return false
	}
	return *c.IsNewToken
}

// GetOriginalPaymentID returns the OriginalPaymentID field if it's non-nil, zero value otherwise.
func (c *CreateResponse) GetOriginalPaymentID() string {
	if c == nil || c.OriginalPaymentID == nil {
		return ""
	}
	return *c.OriginalPaymentID
}

// GetToken returns the Token field if it's non-nil, zero value otherwise.
func (c *CreateResponse) GetToken() string {
	if c == nil || c.Token == nil {
		return ""
	}
	return *c.Token
}

// GetAdditionalAddressInfo returns the AdditionalAddressInfo field if it's non-nil, zero value otherwise.
func (c *Creditor) GetAdditionalAddressInfo() string {
	if c == nil || c.AdditionalAddressInfo == nil {
		return ""
	}
	return *c.AdditionalAddressInfo
}

// GetCity returns the City field if it's non-nil, zero value otherwise.
func (c *Creditor) GetCity() string {
	if c == nil || c.City == nil {
		return ""
	}
	return *c.City
}

// GetCountryCode returns the CountryCode field if it's non-nil, zero value otherwise.
func (c *Creditor) GetCountryCode() string {
	if c == nil || c.CountryCode == nil {
		return ""
	}
	return *c.CountryCode
}

// GetHouseNumber returns the HouseNumber field if it's non-nil, zero value otherwise.
func (c *Creditor) GetHouseNumber() string {
	if c == nil || c.HouseNumber == nil {
		return ""
	}
	return *c.HouseNumber
}

// GetIban returns the Iban field if it's non-nil, zero value otherwise.
func (c *Creditor) GetIban() string {
	if c == nil || c.Iban == nil {
		return ""
	}
	return *c.Iban
}

// GetID returns the ID field if it's non-nil, zero value otherwise.
func (c *Creditor) GetID() string {
	if c == nil || c.ID == nil {
		return ""
	}
	return *c.ID
}

// GetName returns the Name field if it's non-nil, zero value otherwise.
func (c *Creditor) GetName() string {
	if c == nil || c.Name == nil {
		return ""
	}
	return *c.Name
}

// GetReferenceParty returns the ReferenceParty field if it's non-nil, zero value otherwise.
func (c *Creditor) GetReferenceParty() string {
	if c == nil || c.ReferenceParty == nil {
		return ""
	}
	return *c.ReferenceParty
}

// GetReferencePartyID returns the ReferencePartyID field if it's non-nil, zero value otherwise.
func (c *Creditor) GetReferencePartyID() string {
	if c == nil || c.ReferencePartyID == nil {
		return ""
	}
	return *c.ReferencePartyID
}

// GetStreet returns the Street field if it's non-nil, zero value otherwise.
func (c *Creditor) GetStreet() string {
	if c == nil || c.Street == nil {
		return ""
	}
	return *c.Street
}

// GetZip returns the Zip field if it's non-nil, zero value otherwise.
func (c *Creditor) GetZip() string {
	if c == nil || c.Zip == nil {
		return ""
	}
	return *c.Zip
}

// GetMerchantCustomerID returns the MerchantCustomerID field if it's non-nil, zero value otherwise.
func (c *CustomerToken) GetMerchantCustomerID() string {
	if c == nil || c.MerchantCustomerID == nil {
		return ""
	}
	return *c.MerchantCustomerID
}

// GetPersonalInformation returns the PersonalInformation field.
func (c *CustomerToken) GetPersonalInformation() *PersonalInformationToken {
	if c == nil {
		return nil
	}
	return c.PersonalInformation
}

// GetVatNumber returns the VatNumber field if it's non-nil, zero value otherwise.
func (c *CustomerToken) GetVatNumber() string {
	if c == nil || c.VatNumber == nil {
		return ""
	}
	return *c.VatNumber
}

// GetContactDetails returns the ContactDetails field.
func (c *CustomerTokenWithContactDetails) GetContactDetails() *ContactDetailsToken {
	if c == nil {
		return nil
	}
	return c.ContactDetails
}

// GetMerchantCustomerID returns the MerchantCustomerID field if it's non-nil, zero value otherwise.
func (c *CustomerTokenWithContactDetails) GetMerchantCustomerID() string {
	if c == nil || c.MerchantCustomerID == nil {
		return ""
	}
	return *c.MerchantCustomerID
}

// GetPersonalInformation returns the PersonalInformation field.
func (c *CustomerTokenWithContactDetails) GetPersonalInformation() *PersonalInformationToken {
	if c == nil {
		return nil
	}
	return c.PersonalInformation
}

// GetVatNumber returns the VatNumber field if it's non-nil, zero value otherwise.
func (c *CustomerTokenWithContactDetails) GetVatNumber() string {
	if c == nil || c.VatNumber == nil {
		return ""
	}
	return *c.VatNumber
}

// GetAdditionalAddressInfo returns the AdditionalAddressInfo field if it's non-nil, zero value otherwise.
func (d *Debtor) GetAdditionalAddressInfo() string {
	if d == nil || d.AdditionalAddressInfo == nil {
		return ""
	}
	return *d.AdditionalAddressInfo
}

// GetCity returns the City field if it's non-nil, zero value otherwise.
func (d *Debtor) GetCity() string {
	if d == nil || d.City == nil {
		return ""
	}
	return *d.City
}

// GetCountryCode returns the CountryCode field if it's non-nil, zero value otherwise.
func (d *Debtor) GetCountryCode() string {
	if d == nil || d.CountryCode == nil {
		return ""
	}
	return *d.CountryCode
}

// GetFirstName returns the FirstName field if it's non-nil, zero value otherwise.
func (d *Debtor) GetFirstName() string {
	if d == nil || d.FirstName == nil {
		return ""
	}
	return *d.FirstName
}

// GetHouseNumber returns the HouseNumber field if it's non-nil, zero value otherwise.
func (d *Debtor) GetHouseNumber() string {
	if d == nil || d.HouseNumber == nil {
		return ""
	}
	return *d.HouseNumber
}

// GetState returns the State field if it's non-nil, zero value otherwise.
func (d *Debtor) GetState() string {
	if d == nil || d.State == nil {
		return ""
	}
	return *d.State
}

// GetStateCode returns the StateCode field if it's non-nil, zero value otherwise.
func (d *Debtor) GetStateCode() string {
	if d == nil || d.StateCode == nil {
		return ""
	}
	return *d.StateCode
}

// GetStreet returns the Street field if it's non-nil, zero value otherwise.
func (d *Debtor) GetStreet() string {
	if d == nil || d.Street == nil {
		return ""
	}
	return *d.Street
}

// GetSurname returns the Surname field if it's non-nil, zero value otherwise.
func (d *Debtor) GetSurname() string {
	if d == nil || d.Surname == nil {
		return ""
	}
	return *d.Surname
}

// GetSurnamePrefix returns the SurnamePrefix field if it's non-nil, zero value otherwise.
func (d *Debtor) GetSurnamePrefix() string {
	if d == nil || d.SurnamePrefix == nil {
		return ""
	}
	return *d.SurnamePrefix
}

// GetZip returns the Zip field if it's non-nil, zero value otherwise.
func (d *Debtor) GetZip() string {
	if d == nil || d.Zip == nil {
		return ""
	}
	return *d.Zip
}

// GetAlias returns the Alias field if it's non-nil, zero value otherwise.
func (e *EWallet) GetAlias() string {
	if e == nil || e.Alias == nil {
		return ""
	}
	return *e.Alias
}

// GetCustomer returns the Customer field.
func (e *EWallet) GetCustomer() *CustomerToken {
	if e == nil {
		return nil
	}
	return e.Customer
}

// GetData returns the Data field.
func (e *EWallet) GetData() *EWalletData {
	if e == nil {
		return nil
	}
	return e.Data
}

// GetBillingAgreementID returns the BillingAgreementID field if it's non-nil, zero value otherwise.
func (e *EWalletData) GetBillingAgreementID() string {
	if e == nil || e.BillingAgreementID == nil {
		return ""
	}
	return *e.BillingAgreementID
}

// GetMandateSignatureDate returns the MandateSignatureDate field if it's non-nil, zero value otherwise.
func (m *MandateApproval) GetMandateSignatureDate() string {
	if m == nil || m.MandateSignatureDate == nil {
		return ""
	}
	return *m.MandateSignatureDate
}

// GetMandateSignaturePlace returns the MandateSignaturePlace field if it's non-nil, zero value otherwise.
func (m *MandateApproval) GetMandateSignaturePlace() string {
	if m == nil || m.MandateSignaturePlace == nil {
		return ""
	}
	return *m.MandateSignaturePlace
}

// GetMandateSigned returns the MandateSigned field if it's non-nil, zero value otherwise.
func (m *MandateApproval) GetMandateSigned() bool {
	if m == nil || m.MandateSigned == nil {
		return false
	}
	return *m.MandateSigned
}

// GetPaymentProduct705SpecificData returns the PaymentProduct705SpecificData field.
func (m *MandateNonSepaDirectDebit) GetPaymentProduct705SpecificData() *NonSepaDirectDebitPaymentProduct705SpecificData {
	if m == nil {
		return nil
	}
	return m.PaymentProduct705SpecificData
}

// GetPaymentProduct730SpecificData returns the PaymentProduct730SpecificData field.
func (m *MandateNonSepaDirectDebit) GetPaymentProduct730SpecificData() *NonSepaDirectDebitPaymentProduct730SpecificData {
	if m == nil {
		return nil
	}
	return m.PaymentProduct730SpecificData
}

// GetCreditor returns the Creditor field.
func (m *MandateSepaDirectDebit) GetCreditor() *Creditor {
	if m == nil {
		return nil
	}
	return m.Creditor
}

// GetCustomerContractIdentifier returns the CustomerContractIdentifier field if it's non-nil, zero value otherwise.
func (m *MandateSepaDirectDebit) GetCustomerContractIdentifier() string {
	if m == nil || m.CustomerContractIdentifier == nil {
		return ""
	}
	return *m.CustomerContractIdentifier
}

// GetDebtor returns the Debtor field.
func (m *MandateSepaDirectDebit) GetDebtor() *Debtor {
	if m == nil {
		return nil
	}
	return m.Debtor
}

// GetIsRecurring returns the IsRecurring field if it's non-nil, zero value otherwise.
func (m *MandateSepaDirectDebit) GetIsRecurring() bool {
	if m == nil || m.IsRecurring == nil {
		return false
	}
	return *m.IsRecurring
}

// GetMandateApproval returns the MandateApproval field.
func (m *MandateSepaDirectDebit) GetMandateApproval() *MandateApproval {
	if m == nil {
		return nil
	}
	return m.MandateApproval
}

// GetMandateID returns the MandateID field if it's non-nil, zero value otherwise.
func (m *MandateSepaDirectDebit) GetMandateID() string {
	if m == nil || m.MandateID == nil {
		return ""
	}
	return *m.MandateID
}

// GetPreNotification returns the PreNotification field if it's non-nil, zero value otherwise.
func (m *MandateSepaDirectDebit) GetPreNotification() string {
	if m == nil || m.PreNotification == nil {
		return ""
	}
	return *m.PreNotification
}

// GetCustomerContractIdentifier returns the CustomerContractIdentifier field if it's non-nil, zero value otherwise.
func (m *MandateSepaDirectDebitWithoutCreditor) GetCustomerContractIdentifier() string {
	if m == nil || m.CustomerContractIdentifier == nil {
		return ""
	}
	return *m.CustomerContractIdentifier
}

// GetDebtor returns the Debtor field.
func (m *MandateSepaDirectDebitWithoutCreditor) GetDebtor() *Debtor {
	if m == nil {
		return nil
	}
	return m.Debtor
}

// GetIsRecurring returns the IsRecurring field if it's non-nil, zero value otherwise.
func (m *MandateSepaDirectDebitWithoutCreditor) GetIsRecurring() bool {
	if m == nil || m.IsRecurring == nil {
		return false
	}
	return *m.IsRecurring
}

// GetMandateApproval returns the MandateApproval field.
func (m *MandateSepaDirectDebitWithoutCreditor) GetMandateApproval() *MandateApproval {
	if m == nil {
		return nil
	}
	return m.MandateApproval
}

// GetPreNotification returns the PreNotification field if it's non-nil, zero value otherwise.
func (m *MandateSepaDirectDebitWithoutCreditor) GetPreNotification() string {
	if m == nil || m.PreNotification == nil {
		return ""
	}
	return *m.PreNotification
}

// GetAlias returns the Alias field if it's non-nil, zero value otherwise.
func (n *NonSepaDirectDebit) GetAlias() string {
	if n == nil || n.Alias == nil {
		return ""
	}
	return *n.Alias
}

// GetCustomer returns the Customer field.
func (n *NonSepaDirectDebit) GetCustomer() *CustomerToken {
	if n == nil {
		return nil
	}
	return n.Customer
}

// GetMandate returns the Mandate field.
func (n *NonSepaDirectDebit) GetMandate() *MandateNonSepaDirectDebit {
	if n == nil {
		return nil
	}
	return n.Mandate
}

// GetAuthorisationID returns the AuthorisationID field if it's non-nil, zero value otherwise.
func (n *NonSepaDirectDebitPaymentProduct705SpecificData) GetAuthorisationID() string {
	if n == nil || n.AuthorisationID == nil {
		return ""
	}
	return *n.AuthorisationID
}

// GetName returns the Name field.
func (p *PersonalInformationToken) GetName() *PersonalNameToken {
	if p == nil {
		return nil
	}
	return p.Name
}

// GetFirstName returns the FirstName field if it's non-nil, zero value otherwise.
func (p *PersonalNameToken) GetFirstName() string {
	if p == nil || p.FirstName == nil {
		return ""
	}
	return *p.FirstName
}

// GetSurname returns the Surname field if it's non-nil, zero value otherwise.
func (p *PersonalNameToken) GetSurname() string {
	if p == nil || p.Surname == nil {
		return ""
	}
	return *p.Surname
}

// GetSurnamePrefix returns the SurnamePrefix field if it's non-nil, zero value otherwise.
func (p *PersonalNameToken) GetSurnamePrefix() string {
	if p == nil || p.SurnamePrefix == nil {
		return ""
	}
	return *p.SurnamePrefix
}

// GetCard returns the Card field.
func (r *Response) GetCard() *Card {
	if r == nil {
		return nil
	}
	return r.Card
}

// GetEWallet returns the EWallet field.
func (r *Response) GetEWallet() *EWallet {
	if r == nil {
		return nil
	}
	return r.EWallet
}

// GetID returns the ID field if it's non-nil, zero value otherwise.
func (r *Response) GetID() string {
	if r == nil || r.ID == nil {
		return ""
	}
	return *r.ID
}

// GetNonSepaDirectDebit returns the NonSepaDirectDebit field.
func (r *Response) GetNonSepaDirectDebit() *NonSepaDirectDebit {
	if r == nil {
		return nil
	}
	return r.NonSepaDirectDebit
}

// GetOriginalPaymentID returns the OriginalPaymentID field if it's non-nil, zero value otherwise.
func (r *Response) GetOriginalPaymentID() string {
	if r == nil || r.OriginalPaymentID == nil {
		return ""
	}
	return *r.OriginalPaymentID
}

// GetPaymentProductID returns the PaymentProductID field if it's non-nil, zero value otherwise.
func (r *Response) GetPaymentProductID() int32 {
	if r == nil || r.PaymentProductID == nil {
		return 0
	}
	return *r.PaymentProductID
}

// GetSepaDirectDebit returns the SepaDirectDebit field.
func (r *Response) GetSepaDirectDebit() *SepaDirectDebit {
	if r == nil {
		return nil
	}
	return r.SepaDirectDebit
}

// GetAlias returns the Alias field if it's non-nil, zero value otherwise.
func (s *SepaDirectDebit) GetAlias() string {
	if s == nil || s.Alias == nil {
		return ""
	}
	return *s.Alias
}

// GetCustomer returns the Customer field.
func (s *SepaDirectDebit) GetCustomer() *CustomerTokenWithContactDetails {
	if s == nil {
		return nil
	}
	return s.Customer
}

// GetMandate returns the Mandate field.
func (s *SepaDirectDebit) GetMandate() *MandateSepaDirectDebit {
	if s == nil {
		return nil
	}
	return s.Mandate
}

// GetAlias returns the Alias field if it's non-nil, zero value otherwise.
func (s *SepaDirectDebitWithoutCreditor) GetAlias() string {
	if s == nil || s.Alias == nil {
		return ""
	}
	return *s.Alias
}

// GetCustomer returns the Customer field.
func (s *SepaDirectDebitWithoutCreditor) GetCustomer() *CustomerTokenWithContactDetails {
	if s == nil {
		return nil
	}
	return s.Customer
}

// GetMandate returns the Mandate field.
func (s *SepaDirectDebitWithoutCreditor) GetMandate() *MandateSepaDirectDebitWithoutCreditor {
	if s == nil {
		return nil
	}
	return s.Mandate
}

// GetCard returns the Card field.
func (u *UpdateRequest) GetCard() *Card {
	if u == nil {
		return nil
	}
	return u.Card
}

// GetEWallet returns the EWallet field.
func (u *UpdateRequest) GetEWallet() *EWallet {
	if u == nil {
		return nil
	}
	return u.EWallet
}

// GetNonSepaDirectDebit returns the NonSepaDirectDebit field.
func (u *UpdateRequest) GetNonSepaDirectDebit() *NonSepaDirectDebit {
	if u == nil {
		return nil
	}
	return u.NonSepaDirectDebit
}

// GetPaymentProductID returns the PaymentProductID field if it's non-nil, zero value otherwise.
func (u *UpdateRequest) GetPaymentProductID() int32 {
	if u == nil || u.PaymentProductID == nil {
		return 0
	}
	return *u.PaymentProductID
}

// GetSepaDirectDebit returns the SepaDirectDebit field.
func (u *UpdateRequest) GetSepaDirectDebit() *SepaDirectDebitWithoutCreditor {
	if u == nil {
		return nil
	}
	return u.SepaDirectDebit
}
