// Copyright 2017 The go-github AUTHORS. All rights reserved.
//
// Use of this source code is governed by a BSD-style
// license that can be found in the LICENSE file.

// Code generated by gen-accessors; DO NOT EDIT.

package webhooks

// GetAPIVersion returns the APIVersion field if it's non-nil, zero value otherwise.
func (e *Event) GetAPIVersion() string {
	if e == nil || e.APIVersion == nil {
		return ""
	}
	return *e.APIVersion
}

// GetCreated returns the Created field if it's non-nil, zero value otherwise.
func (e *Event) GetCreated() string {
	if e == nil || e.Created == nil {
		return ""
	}
	return *e.Created
}

// GetID returns the ID field if it's non-nil, zero value otherwise.
func (e *Event) GetID() string {
	if e == nil || e.ID == nil {
		return ""
	}
	return *e.ID
}

// GetMerchantID returns the MerchantID field if it's non-nil, zero value otherwise.
func (e *Event) GetMerchantID() string {
	if e == nil || e.MerchantID == nil {
		return ""
	}
	return *e.MerchantID
}

// GetType returns the Type field if it's non-nil, zero value otherwise.
func (e *Event) GetType() string {
	if e == nil || e.Type == nil {
		return ""
	}
	return *e.Type
}
